# -*- coding: utf-8 -*-
"""ybus_app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLQ-wDK2-b23gvPkacr2F6D6Sle-EW0R
"""

# pip install streamlit pandas numpy scipy openpyxl

import subprocess
subprocess.Popen(['streamlit', 'run', 'ybus_app.py'])

import streamlit as st
import pandas as pd
import numpy as np
import scipy.sparse as sp

# --- Page Configuration ---
st.set_page_config(page_title="Y-Bus Generator", layout="wide")

st.title("⚡ Power System Y-Bus Matrix Builder")
st.markdown("Enter your transmission line data below to generate the **Bus Admittance Matrix ($Y_{bus}$)** instantly.")

# --- Helper Functions ---
def build_ybus(df):
    """Core logic to build Y-Bus from DataFrame"""
    # 1. Identify System Size
    n_buses = int(max(df['From_Bus'].max(), df['To_Bus'].max()))

    # 2. Extract Data
    R = df['R_pu'].values
    X = df['X_pu'].values
    B = df['B_Total_pu'].values

    # 3. Calculate Primitives
    Z = R + 1j * X
    y_series = 1 / Z
    b_half = 1j * B / 2

    # 4. Build Matrix (Direct Method)
    Y_bus = np.zeros((n_buses, n_buses), dtype=complex)

    for k in range(len(df)):
        i = int(df.iloc[k]['From_Bus']) - 1
        j = int(df.iloc[k]['To_Bus']) - 1

        y = y_series[k]
        b = b_half[k]

        # Off-Diagonal
        Y_bus[i, j] -= y
        Y_bus[j, i] -= y

        # Diagonal
        Y_bus[i, i] += (y + b)
        Y_bus[j, j] += (y + b)

    return Y_bus, n_buses

def format_complex_matrix(matrix):
    """Converts complex numbers to readable strings for display"""
    df_disp = pd.DataFrame(matrix)
    # Format as 'Real ± jImag'
    return df_disp.applymap(lambda x: f"{x.real:.4f} {'+' if x.imag >= 0 else '-'} {abs(x.imag):.4f}j")

# --- Sidebar: Input Method ---
st.sidebar.header("Input Options")
input_method = st.sidebar.radio("Choose how to enter data:", ["Edit Table Manually", "Upload Excel/CSV File"])

# --- Main Input Section ---
st.subheader("1. Transmission Line Data")

# Default Data (4-Bus System)
default_data = pd.DataFrame({
    'From_Bus': [1, 1, 1, 2, 3],
    'To_Bus':   [2, 3, 4, 3, 4],
    'R_pu':     [0.02, 0.08, 0.04, 0.06, 0.02],
    'X_pu':     [0.06, 0.24, 0.12, 0.18, 0.08],
    'B_Total_pu': [0.06, 0.05, 0.04, 0.04, 0.03]
})

if input_method == "Edit Table Manually":
    st.info("💡 Tip: You can copy-paste from Excel directly into this table. Click '+' to add rows.")
    # Editable Data Table
    df_input = st.data_editor(default_data, num_rows="dynamic", use_container_width=True)

else: # File Upload
    uploaded_file = st.sidebar.file_uploader("Upload your network data", type=["csv", "xlsx"])
    if uploaded_file:
        try:
            if uploaded_file.name.endswith('.csv'):
                df_input = pd.read_csv(uploaded_file)
            else:
                df_input = pd.read_excel(uploaded_file)
            st.success("File uploaded successfully!")
            st.dataframe(df_input)
        except Exception as e:
            st.error(f"Error reading file: {e}")
            df_input = None
    else:
        st.warning("Please upload a file to proceed.")
        df_input = None

# --- Calculation Trigger ---
if df_input is not None and not df_input.empty:
    if st.button("🚀 Construct Y-Bus Matrix", type="primary"):
        try:
            # Run Calculation
            Y_matrix, n_buses = build_ybus(df_input)

            st.divider()
            st.subheader(f"2. Result: {n_buses} x {n_buses} Y-Bus Matrix")

            # Display Options Tabs
            tab1, tab2, tab3 = st.tabs(["📄 Formatted View", "🔢 Raw Complex Values", "📉 Sparsity Plot"])

            with tab1:
                st.write("Readable format (Real ± Imag):")
                st.dataframe(format_complex_matrix(Y_matrix), use_container_width=True)

            with tab2:
                st.write("Raw data for copying (Python/Matlab format):")
                st.dataframe(pd.DataFrame(Y_matrix), use_container_width=True)

            with tab3:
                import matplotlib.pyplot as plt
                fig, ax = plt.subplots()
                ax.spy(Y_matrix, markersize=10, color='crimson')
                ax.set_title(f"Sparsity Pattern (Non-zero elements)")
                ax.grid(True)
                st.pyplot(fig)

            # Download Button
            csv_output = pd.DataFrame(Y_matrix).to_csv().encode('utf-8')
            st.download_button(
                label="📥 Download Matrix as CSV",
                data=csv_output,
                file_name="ybus_matrix.csv",
                mime="text/csv",
            )

        except Exception as e:
            st.error(f"Calculation Error: {e}")
            st.error("Please check that your input data has columns: 'From_Bus', 'To_Bus', 'R_pu', 'X_pu', 'B_Total_pu'")

# !streamlit run ybus_app.py

